# Generated by Django 3.2 on 2022-06-28 09:14

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='avatar/%Y', variations={'thumb_400x400': (400, 400), 'thumb_50x50': (50, 50, True)}, verbose_name='个人头像'),
        ),
    ]
