# Generated by Django 4.0.3 on 2022-05-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_banner'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='lf_banner',
        ),
    ]
