# Generated by Django 3.2 on 2022-06-22 06:34

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='详情介绍'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='章节介绍'),
        ),
        migrations.AlterField(
            model_name='coursedirection',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='方向描述'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='orders',
            field=models.SmallIntegerField(default=1, verbose_name='第几课时'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='brief',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1024, verbose_name='讲师描述'),
        ),
        migrations.AlterModelTable(
            name='course',
            table='fg_course_info',
        ),
        migrations.AlterModelTable(
            name='coursecategory',
            table='fg_course_category',
        ),
        migrations.AlterModelTable(
            name='coursechapter',
            table='fg_course_chapter',
        ),
        migrations.AlterModelTable(
            name='coursedirection',
            table='fg_course_direction',
        ),
        migrations.AlterModelTable(
            name='courselesson',
            table='fg_course_lesson',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='fg_teacher',
        ),
    ]
